language: node_js
node_js:
    - "node"
    - "14"
    - "12"
services: mongodb

env:
  - JWT_SECRET='longsecretlongsecretlongsecretlongsecretlongsecretlongsecret1234'
  - SENDGRID_API_KEY='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'

before_script:
    - npm install 

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov



